import { Question, PricingPlan } from './types';
import { CreditCard, Smartphone, Wallet } from 'lucide-react';

export const QUESTIONS: Question[] = [
  // Step 1: Date of Birth
  {
    id: 1,
    key: 'dob',
    type: 'date',
  },
  // Step 2: Height
  {
    id: 2,
    key: 'height',
    type: 'measurement',
    units: [{ label: 'cm', value: 'cm' }, { label: 'ft', value: 'ft' }],
    defaultUnit: 'cm',
    min: 130,
    max: 210,
    defaultValue: 170,
  },
  // Step 3: Current Weight
  {
    id: 3,
    key: 'current_weight',
    type: 'measurement',
    units: [{ label: 'kg', value: 'kg' }, { label: 'lbs', value: 'lbs' }],
    defaultUnit: 'kg',
    min: 40,
    max: 180,
  },
  // Step 4: Goal Weight
  {
    id: 4,
    key: 'target_weight',
    type: 'measurement',
    units: [{ label: 'kg', value: 'kg' }, { label: 'lbs', value: 'lbs' }],
    defaultUnit: 'kg',
    min: 40,
    max: 180,
  },
  // Step 5: Body Type
  {
    id: 5,
    key: 'body_type',
    type: 'choice',
    options: [
      { value: 'skinny', labelEn: 'Skinny', labelAr: 'نحيف' },
      { value: 'regular', labelEn: 'Regular', labelAr: 'عادي' },
      { value: 'extra', labelEn: 'Extra', labelAr: 'ممتلئ' },
    ],
  },
  // Step 6: Desired Body Type
  {
    id: 6,
    key: 'desired_body_type',
    type: 'choice',
    options: [
      { value: 'cut', labelEn: 'Cut', labelAr: 'جسم مقسم' },
      { value: 'lean_bulk', labelEn: 'Lean Bulk', labelAr: 'ضخامة عضلية صافية' },
      { value: 'extra_bulk', labelEn: 'Extra Bulk', labelAr: 'ضخامة فائقة' },
    ],
  },
  // Step 7: Target Zone
  {
    id: 7,
    key: 'target_zone',
    type: 'choice',
    options: [
      { value: 'arms', labelEn: 'Arms', labelAr: 'الأذرع' },
      { value: 'chest', labelEn: 'Chest', labelAr: 'الصدر' },
      { value: 'abs', labelEn: 'Abs', labelAr: 'البطن' },
      { value: 'legs', labelEn: 'Legs', labelAr: 'الأرجل' },
      { value: 'full_body', labelEn: 'Full Body', labelAr: 'الجسم كامل' },
    ],
  },
  // Step 8: Main Goal
  {
    id: 8,
    key: 'main_goal',
    type: 'choice',
    options: [
      { value: 'basics', labelEn: 'Learn the Basics', labelAr: 'تعلم الأساسيات' },
      { value: 'lose_weight', labelEn: 'Lose Weight', labelAr: 'إنقاص الوزن' },
      { value: 'gain_weight', labelEn: 'Gain Weight', labelAr: 'زيادة الوزن' },
      { value: 'muscle_mass', labelEn: 'Gain Muscle Mass', labelAr: 'زيادة الكتلة العضلية' },
      { value: 'strength', labelEn: 'Strength Builder', labelAr: 'بناء القوة' },
      { value: 'shredded', labelEn: 'Get Shredded', labelAr: 'تنشيف الجسم' },
      { value: 'keep_fit', labelEn: 'Keep Fit', labelAr: 'الحفاظ على اللياقة' },
    ],
  },
  // Step 9: Training Goal
  {
    id: 9,
    key: 'training_goal',
    type: 'choice',
    options: [
      { value: 'keep_fit', labelEn: 'Keep Fit', labelAr: 'الحفاظ على اللياقة' },
      { value: 'power', labelEn: 'Power Training', labelAr: 'تدريب القوة' },
      { value: 'resistance', labelEn: 'Resistance', labelAr: 'المقاومة' },
    ],
  },
  // Step 10: Motivation
  {
    id: 10,
    key: 'motivation',
    type: 'choice',
    options: [
      { value: 'health', labelEn: 'Improving Health', labelAr: 'تحسين الصحة' },
      { value: 'immune', labelEn: 'Boosting Immune System', labelAr: 'تعزيز الجهاز المناعي' },
      { value: 'looks', labelEn: 'Looking Better', labelAr: 'تحسين المظهر' },
      { value: 'strength_endurance', labelEn: 'Building Strength and Endurance', labelAr: 'بناء القوة والتحمل' },
      { value: 'libido', labelEn: 'Boosting Libido', labelAr: 'تعزيز الطاقة والحيوية' },
    ],
  },
  // Step 11: Fitness Level
  {
    id: 11,
    key: 'fitness_level',
    type: 'choice',
    options: [
      { value: 'beginner', labelEn: 'Beginner (I’m new to fitness)', labelAr: 'مبتدئ (جديد في اللياقة)' },
      { value: 'intermediate', labelEn: 'Intermediate (I train 2-3 times a week)', labelAr: 'متوسط (أتدرب 2-3 مرات أسبوعياً)' },
      { value: 'advanced', labelEn: 'Advanced (I train regularly)', labelAr: 'متقدم (أتدرب بانتظام)' },
    ],
  },
  // Step 12: Walking
  {
    id: 12,
    key: 'walking',
    type: 'choice',
    options: [
      { value: 'less_1', labelEn: 'Less than 1 hour', labelAr: 'أقل من ساعة' },
      { value: '1_2', labelEn: '1 - 2 hours', labelAr: '1 - 2 ساعة' },
      { value: 'more_2', labelEn: 'More than 2 hours', labelAr: 'أكثر من ساعتين' },
    ],
  },
  // Step 13: Push-ups
  {
    id: 13,
    key: 'pushups',
    type: 'choice',
    options: [
      { value: 'less_12', labelEn: 'Less than 12', labelAr: 'أقل من 12' },
      { value: '13_20', labelEn: '13 - 20', labelAr: '13 - 20' },
      { value: 'more_21', labelEn: 'More than 21', labelAr: 'أكثر من 21' },
      { value: 'unknown', labelEn: 'I don’t know', labelAr: 'لا أعرف' },
    ],
  },
  // Step 14: Sedentary
  {
    id: 14,
    key: 'sedentary',
    type: 'choice',
    options: [
      { value: 'yes', labelEn: 'Yes', labelAr: 'نعم' },
      { value: 'no', labelEn: 'No', labelAr: 'لا' },
    ],
  },
  // Step 15: Water
  {
    id: 15,
    key: 'water',
    type: 'choice',
    options: [
      { value: 'tea_coffee', labelEn: 'I only drink tea and coffee', labelAr: 'أشرب الشاي والقهوة فقط' },
      { value: 'less_2', labelEn: 'Fewer than 2 glasses of water', labelAr: 'أقل من كوبين ماء' },
      { value: '2_6', labelEn: '2-6 glasses of water', labelAr: '2-6 أكواب ماء' },
      { value: '7_10', labelEn: '7-10 glasses of water', labelAr: '7-10 أكواب ماء' },
      { value: 'more_10', labelEn: 'More than 10 glasses of water', labelAr: 'أكثر من 10 أكواب ماء' },
    ],
  },
  // Step 16: Sleep
  {
    id: 16,
    key: 'sleep',
    type: 'choice',
    options: [
      { value: 'less_5', labelEn: 'Fewer than 5 hours', labelAr: 'أقل من 5 ساعات' },
      { value: '5_6', labelEn: 'Between 5 - 6 hours', labelAr: 'بين 5 - 6 ساعات' },
      { value: '7_8', labelEn: 'Between 7 - 8 hours', labelAr: 'بين 7 - 8 ساعات' },
      { value: 'over_8', labelEn: 'Over 8 hours', labelAr: 'أكثر من 8 ساعات' },
    ],
  },
  // Step 17: Between Meals
  {
    id: 17,
    key: 'between_meals',
    type: 'choice',
    options: [
      { value: 'sleepy', labelEn: 'I get sleepy when I’m hungry', labelAr: 'أشعر بالنعاس عندما أجوع' },
      { value: 'tired_after', labelEn: 'I’m tired after I eat', labelAr: 'أشعر بالتعب بعد الأكل' },
      { value: 'enough_energy', labelEn: 'I have enough energy', labelAr: 'لدي طاقة كافية' },
      { value: 'tired_overeat', labelEn: 'I feel tired when I overeat', labelAr: 'أتعب عند الإفراط في الأكل' },
      { value: 'irritable', labelEn: 'I feel irritable when I’m hungry', labelAr: 'أشعر بالعصبية عندما أجوع' },
    ],
  },
];

export const PLANS: PricingPlan[] = [
  {
    id: '1_month',
    durationMonths: 1,
    price: '$19.99',
    labelEn: 'Monthly',
    labelAr: 'شهري',
  },
  {
    id: '3_month',
    durationMonths: 3,
    price: '$39.99',
    labelEn: '3 Months',
    labelAr: '3 أشهر',
    tagEn: 'Most Popular',
    tagAr: 'الأكثر شيوعاً',
    isBestValue: true,
  },
  {
    id: '6_month',
    durationMonths: 6,
    price: '$59.99',
    labelEn: '6 Months',
    labelAr: '6 أشهر',
    tagEn: 'Save More',
    tagAr: 'وفر أكثر',
  },
  {
    id: '12_month',
    durationMonths: 12,
    price: '$79.99',
    labelEn: 'Yearly',
    labelAr: 'سنوي',
    tagEn: 'Best Deal',
    tagAr: 'أفضل عرض',
  },
];

export const TRANSLATIONS = {
  en: {
    splashTagline: 'No more excuses',
    landingHeadline: 'Answer the questions\nand get a custom plan for your body, goal & time',
    landingBullet1: 'Your Custom Workout Schedule',
    landingBullet2: 'Your Custom Nutrition Plan',
    landingBullet3: 'Product Calorie Scanner',
    landingBullet4: 'Tracking Calories, Weight & BMI',
    landingBullet5: 'Everything you need to reach your goal easily',
    landingTrust: '100% Private & Secure • No Credit Card Required',
    ctaStart: 'Start Now',
    genderSelect: 'Choose Gender',
    man: 'Man',
    woman: 'Woman',
    continue: 'Continue',
    back: 'Back',
    loading1: 'Analyzing your inputs...',
    loading2: 'Calculating metabolic rate...',
    loading3: 'Building weekly schedule...',
    planReady: 'Your Plan Is Ready!',
    planSummary: 'Personalized Plan Summary',
    unlockPlan: 'Unlock My Full Plan',
    guarantee: '7-Day Money-Back Guarantee',
    paymentSecure: 'Guaranteed Safe Checkout',
    checkoutHeader: 'Create Account',
    firstName: 'First Name',
    phoneNumber: 'Phone Number',
    email: 'Email (Optional)',
    payNow: 'Complete Secure Payment',
    successTitle: 'Account Created!',
    successSub: 'Your plan is waiting in the app.',
    download: 'Download App',
    goToLogin: 'Continue to Login',
    bmi: 'Estimated BMI',
    offerTimer: 'Offer reserved for',
    paymentMethods: 'Secure Payment Methods',
    dob: 'Date of Birth',
    height: 'How tall are you?',
    weight: 'Select Current Weight',
    goalWeight: 'Select Goal Weight',
    day: 'Day',
    month: 'Month',
    year: 'Year',
    // New Translations
    aiProcessing: 'AI Engine v2.4 Processing',
    goalLabel: 'Goal',
    bodyTypeLabel: 'Body Type',
    successRate: 'Success Rate',
    normal: 'Normal',
    underweight: 'Underweight',
    overweight: 'Overweight',
    obese: 'Obese',
    terms: 'By continuing you agree to our Terms of Service. Subscription auto-renews unless canceled.',
    payIcon: 'PAY',
    changePackage: 'Change Package',
  },
  ar: {
    splashTagline: 'لامزيد من الأعذار',
    landingHeadline: 'جاوب على الأسئلة\nو احصل على خطة مخصصة لجسمك وهدفك ووقتك',
    landingBullet1: 'جدول تمارين خاص بك',
    landingBullet2: 'جدول تغذية خاص بك',
    landingBullet3: 'قارئ سعرات المنتجات',
    landingBullet4: 'متابعة السعرات والوزن وكتلة الجسم',
    landingBullet5: 'وكل ما تحتاجه للوصول لهدفك بسهولة',
    landingTrust: '100% خاص وآمن • لا يتطلب بطاقة ائتمان',
    ctaStart: 'ابدأ الآن',
    genderSelect: 'اختر الجنس',
    man: 'رجل',
    woman: 'امرأة',
    continue: 'متابعة',
    back: 'رجوع',
    loading1: 'جاري تحليل إجاباتك...',
    loading2: 'حساب معدل الأيض...',
    loading3: 'بناء الجدول الأسبوعي...',
    planReady: 'خطتك جاهزة!',
    planSummary: 'ملخص خطتك الشخصية',
    unlockPlan: 'افتح خطتي الكاملة',
    guarantee: 'ضمان استرداد الأموال لمدة 7 أيام',
    paymentSecure: 'دفع آمن مضمون',
    checkoutHeader: 'إنشاء حساب',
    firstName: 'الاسم الأول',
    phoneNumber: 'رقم الهاتف',
    email: 'البريد الإلكتروني (اختياري)',
    payNow: 'إتمام الدفع الآمن',
    successTitle: '!تم إنشاء الحساب',
    successSub: '.خطتك بانتظارك في التطبيق',
    download: 'تحميل التطبيق',
    goToLogin: 'المتابعة لتسجيل الدخول',
    bmi: 'مؤشر كتلة الجسم التقديري',
    offerTimer: 'العرض متاح لمدة',
    paymentMethods: 'طرق الدفع الآمنة',
    dob: 'تاريخ الميلاد',
    height: 'كم طولك؟',
    weight: 'اختر وزنك الحالي',
    goalWeight: 'اختر الوزن المستهدف',
    day: 'يوم',
    month: 'شهر',
    year: 'سنة',
    // New Translations
    aiProcessing: 'جاري معالجة بياناتك لتحصل على الخطة المناسبة لك.',
    goalLabel: 'الهدف',
    bodyTypeLabel: 'نوع الجسم',
    successRate: 'نسبة النجاح',
    normal: 'طبيعي',
    underweight: 'نحيف',
    overweight: 'زيادة وزن',
    obese: 'سمنة',
    terms: 'بالمتابعة، أنت توافق على شروط الخدمة. يتجدد الاشتراك تلقائياً ما لم يتم إلغاؤه.',
    payIcon: 'دفع',
    changePackage: 'تغيير الباقة',
  }
};